# general settings
name: pixelcnn_multi_8
model_type: PixelCNN_Model
scale: 1
num_gpu: auto  # auto: can infer from your visible devices automatically. official: 4 GPUs
manual_seed: 0

# ----------------- options for synthesizing training data in RealESRNetModel ----------------- #
gt_usm: False  # USM the ground-truth

gt_size: 256
queue_size: 160

# dataset and data loader settings
datasets:
  train:
    name: FFHQ
    type: VQGANPairedDataset
    dataroot_gt: /root/cloud/data-collection/ffhq-dataset/images256x256
    meta_info: /root/picasso/韩昊天/画质修复/VQGAN/options/meta_info_ffhq.txt
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: True
    use_rot: False

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 10
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Uncomment these for validation

# network structures
network_g:
  type: PixelCNNWithEmbedding
  n_blocks: 35
  p: 256
  linear_dim: 256
  bn: True
  color_level: 256


# network structures
network_vae:
  type: VQVAE_multi_codebook
  input_dim: 48
  dim: 64
  n_embedding: 256
  n_codebook: 8


# path
path:
  pretrain_network_g: ~
  pretrain_network_vae: /root/picasso/韩昊天/画质修复/VQGAN/experiments/VQVAE_Multi_FFHQ_codebook8/models/net_g_latest.pth
  strict_load_g: False
  resume_state: ~
  ignore_resume_networks: network_vae
 
# training settings
train:
  ema_decay: 0.999

  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [500000,700000]
    gamma: 0.5

  encoder_iter: 100000
  total_iter: 1000000
  lr_encoder: !!float 2e-4
  lr_sr: !!float 2e-4
  gamma_encoder: 0.1
  gamma_sr: 0.5
  lr_decay_encoder: 60000
  lr_decay_sr: 600000
  warmup_iter: -1  # no warm up

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  kd_opt:
    type: KDLoss
    loss_weight: 1
    temperature: 0.15

# Uncomment these for validation
# validation settings


# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
